---
- name: Create Elastic Group for Nomad Clients
  connection: local
  gather_facts: False
  hosts: localhost
  vars:
    userdata: "{{ lookup('file', 'user-data.sh') }}"
  tasks:
    - name: "create elastic group for clients"
      spotinst_aws_elastigroup:
        user_data: "{{ userdata | b64encode }}"
        state: present
        risk: 100
        availability_vs_cost: balanced
        availability_zones:
          - name: "{{ availability_zone_region }}"
            subnet_id: "{{ availability_zone_subnet_id }}"
        image_id: "{{ ami_id }}"
        key_pair: "{{ key_name }}"
        min_size: "{{ spotinst_min }}"
        max_size: "{{ spotinst_max }}"
        target: "{{ spotinst_target }}"
        unit: instance
        monitoring: True
        name: "{{ spotinst_group_name }}"
        on_demand_instance_type: "{{ on_demand_instance_type }}"
        product: "{{product_type}}"
        # - tal-lb-1
        security_group_ids:
          - "{{ security_group }}"
        spot_instance_types: "{{ instance_types }}"
        wait_for_instances: True
        wait_timeout: 600
        tags:
          - Name: "{{ spotinst_group_name }}"
        #state: absent
        block_device_mappings:
          - device_name: '/dev/xvda'
            ebs:
              volume_size: 80
              volume_type: gp2
              deleteOnTermination: True
      register: ec2